avio: vpp: fix vsxxx build error due to undefined function and macro
ERROR: modpost: "NTZ_MV_VPP_UpdateGamma" [drivers/synaptics/soc/berlin/modules/avio/avio.ko] undefined!
error: 'SYNA_GAMMA_LUT_SIZE' undeclared (first use in this function)

Change-Id: I220c64797eafe02ae4b624eb5bf5432b086bf35e
Reviewed-on: https://gerrit-sha.synaptics.com/gerrit/294150
Reviewed-by: Jagath JogJ <Jagath.JogJ@synaptics.com>
Reviewed-by: Shanmugam Ramachandran <Shanmugam.Ramachandran@synaptics.com>