tsp:fix compile error when CONFIG_OPTEE enable
tsp_core.c: In function â€˜berlin_tsp_probeâ€™:
tsp/tsp_core.c:627:1: error: label â€˜err_prob_device_0â€™
defined but not used [-Werror=unused-label]

Change-Id: I276aa0fc2872409b775568ff4aa68c7d72b691c0
Reviewed-on: https://gerrit-sha.synaptics.com/gerrit/293832
Reviewed-by: Xu Hu <Xu.Hu@synaptics.com>
Reviewed-by: Kaicheng Xie <Kaicheng.Xie@synaptics.com>
Reviewed-by: Jisheng Zhang <Jisheng.Zhang@synaptics.com>