rogue_ws: Fix build error caused by PVRSRV_TRACE_ROGUE_EVENTS
Fix below errors:

In file included from linux_6_12/main/include/trace/trace_events.h:445,
                 from linux_6_12/main/include/trace/define_trace.h:102,
                 from linux_6_12/main/drivers/synaptics/soc/berlin/modules/rogue_ws/include/pvr_fence_trace.h:230,
                 from linux_6_12/main/drivers/synaptics/soc/berlin/modules/rogue_ws/src/pvr_fence.c:55:
linux_6_12/main/drivers/synaptics/soc/berlin/modules/rogue_ws/include/./pvr_fence_trace.h:78:1: error: macro "__assign_str" passed 2 arguments, but takes just 1
   78 | );
      | ^~
In file included from linux_6_12/main/include/trace/trace_events.h:378:
linux_6_12/main/include/trace/stages/stage6_event_callback.h:34:9: note: macro "__assign_str" defined here
   34 | #define __assign_str(dst)                                               \
      |         ^~~~~~~~~~~~                                                                                                                                                                      linux_6_12/main/drivers/synaptics/soc/berlin/modules/rogue_ws/include/./pvr_fence_trace.h: In function ‘do_trace_event_raw_event_pvr_fence_context’:
linux_6_12/main/drivers/synaptics/soc/berlin/modules/rogue_ws/include/./pvr_fence_trace.h:69:17: error: unknown type name ‘__assign_str’; did you mean ‘pvr_assign_str’?
   69 |                 __assign_str(name, fctx->name)
      |                 ^~~~~~~~~~~~
linux_6_12/main/include/trace/trace_events.h:405:11: note: in definition of macro ‘__DECLARE_EVENT_CLASS’
  405 |         { assign; }                                                     \
      |           ^~~~~~
linux_6_12/main/include/trace/trace_events.h:413:23: note: in expansion of macro ‘PARAMS’
  413 |                       PARAMS(assign), PARAMS(print))                    \
      |                       ^~~~~~
linux_6_12/main/drivers/synaptics/soc/berlin/modules/rogue_ws/include/./pvr_fence_trace.h:58:1: note: in expansion of macro ‘DECLARE_EVENT_CLASS’
   58 | DECLARE_EVENT_CLASS(pvr_fence_context,
      | ^~~~~~~~~~~~~~~~~~~
linux_6_12/main/drivers/synaptics/soc/berlin/modules/rogue_ws/include/./pvr_fence_trace.h:68:9: note: in expansion of macro ‘TP_fast_assign’
   68 |         TP_fast_assign(
      |         ^~~~~~~~~~~~~~
linux_6_12/main/drivers/synaptics/soc/berlin/modules/rogue_ws/include/./pvr_fence_trace.h:70:52: error: expected ‘)’ before ‘->’ token
   70 |                 pvr_context_value_str(fctx, __entry->val,
      |                                                    ^~
linux_6_12/main/include/trace/trace_events.h:405:11: note: in definition of macro ‘__DECLARE_EVENT_CLASS’
  405 |         { assign; }                                                     \
      |           ^~~~~~
linux_6_12/main/include/trace/trace_events.h:413:23: note: in expansion of macro ‘PARAMS’
...

Change-Id: If4a311ed0db9f9e7c994da9ad2f1f304ee8e7c75
Signed-off-by: Jisheng Zhang <jszhang@kernel.org>
Reviewed-on: https://gerrit-sha.synaptics.com/gerrit/281927
Reviewed-by: Lijo Varghese <Lijo.Varghese@synaptics.com>
Reviewed-by: Jisheng Zhang <Jisheng.Zhang@synaptics.com>